version: '2.1'

networks:
  microservice:
    driver: bridge

services:
  fuseki:
    image: secoresearch/fuseki
    environment:
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./backend/fuseki:/fuseki-base
    ports:
      - "3030:3030"
    networks:
      - microservice
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservice
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./backend/mongodb/database:/data/db
    ports:
      - 27016:27017
    restart: unless-stopped
    networks:
      - microservice
